export const SET_INFORMATION_BASIC = 'SET_INFORMATION_BASIC';
export const SET_INFORMATION_EDUCATION = 'SET_INFORMATION_EDUCATION';
export const SET_INFORMATION_EXPERIENCE = 'SET_INFORMATION_EXPERIENCE';
